# Generated by Django 3.2.19 on 2023-06-04 07:46

import django.core.validators
from django.db import migrations, models
import skyloov.shops.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('price_fabric', skyloov.shops.fields.PriceField(decimal_places=0, max_digits=20, verbose_name='Price Fabric')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Discount Price')),
                ('brand', models.CharField(choices=[('lennar', 'Lennar'), ('dr_horton', 'DR Horton'), ('pulte_homes', 'Pulte Homes'), ('toll_brothers', 'Toll Brothers'), ('kb_home', 'KB Home')], max_length=100, verbose_name='Brand')),
                ('category', models.CharField(choices=[('single_family', 'Single_family'), ('condominiums', 'Condominiums'), ('townhouses', 'Townhouses'), ('duplexes', 'Duplexes'), ('apartments', 'Apartments'), ('villas', 'Villas'), ('bungalows', 'Bungalows'), ('mansions', 'Mansions'), ('tiny', 'Tiny'), ('houses', 'Houses'), ('mobile', 'Mobile'), ('homes', 'Homes')], max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
