# Generated by Django 3.2.19 on 2023-06-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('asus', 'Asus'), ('microsoft', 'Microsoft'), ('google', 'Google')], max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('smartwatch', 'Smartwatch'), ('tablet', 'Tablet'), ('smart_speaker', 'Smart Speaker')], max_length=100, verbose_name='Category'),
        ),
    ]
