# Generated by Django 3.2.19 on 2023-06-06 21:51

from django.db import migrations
import skyloov.shops.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20230606_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=skyloov.shops.fields.PriceField(decimal_places=0, max_digits=20, verbose_name='Price'),
        ),
    ]
