# Generated by Django 3.2.19 on 2023-06-07 09:59

from django.db import migrations
import django.db.models.deletion
import skyloov.utilities.db.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('shops', '0012_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_original',
            field=skyloov.utilities.db.fields.file_field.FileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_image_original', to='files.filemodel', verbose_name='Image Original'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_thumbnail',
            field=skyloov.utilities.db.fields.file_field.FileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_image_thumbnail', to='files.filemodel', verbose_name='Image Thumbnail'),
        ),
    ]
